root: true
rules:
  comma-dangle: error
  comma-style:
    - error
    - last
  eol-last: error
  indent:
    - error
    - 2
    - SwitchCase: 1
  no-param-reassign: error
  no-trailing-spaces: error
  no-unused-vars:
    - error
    - vars: all
      args: none
      ignoreRestSiblings: true
